---
# Django CRM Staging Inventory
all:
  children:
    webservers:
      hosts:
        server:
          ansible_host: "YOUR_DROPLET_IP"
          domain_name: "crm.yourdomain.com"
  vars:
    ansible_user: root
