---
all:
  children:
    webservers:
      hosts:
        server:
          ansible_host: 165.227.174.42
          domain_name: crm.hyperlocal.cloud
          mount_point:
          sentry_dsn: ""
  vars:
    ansible_user: root
