---
# Application deployment playbook

- hosts: webservers
  vars_files:
    - vars/appserver_vars.yml
  gather_facts: True
  become: True

  pre_tasks:
    - name: Check for single host
      fail: msg="Single host check failed."
      when: play_hosts|length != 1
    - debug: msg="I got executed!"

  roles:
    - app
